depmod -a

# Enable bmc vlan_ip service
systemctl enable bmc_vlan.service

systemctl enable platform-modules-migaloo.service
systemctl start platform-modules-migaloo.service

/usr/local/bin/platform_api_mgnt.sh install

# Enable platform-sync_bmc-timer
# systemctl enable sync_bmc.timer
# systemctl start sync_bmc.timer

# Enable heartbeat timer
systemctl enable bmc_wdt.service
systemctl start bmc_wdt.service
